-- Lead storage for the optional Supabase integration.
-- Run this once in Supabase Dashboard -> SQL Editor.

create table if not exists public.leads (
    id bigint generated by default as identity primary key,
    website_key text not null unique,
    business_name text not null default 'Unknown',
    niche text not null default '',
    website text not null default '',
    emails jsonb not null default '[]'::jsonb,
    whatsapp_numbers jsonb not null default '[]'::jsonb,
    instagram_handles jsonb not null default '[]'::jsonb,
    linkedin_urls jsonb not null default '[]'::jsonb,
    phones jsonb not null default '[]'::jsonb,
    source_query text not null default '',
    quality_label text not null default 'low',
    quality_score integer not null default 0,
    email_origin text not null default 'scraped',
    scraped_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists leads_niche_idx on public.leads (niche);
create index if not exists leads_quality_score_idx on public.leads (quality_score desc);
create index if not exists leads_scraped_at_idx on public.leads (scraped_at desc);

-- The Python server uses a Supabase secret key, which bypasses RLS. Keep RLS
-- enabled so a publishable/anon key cannot read the private lead database.
alter table public.leads enable row level security;

create or replace function public.set_leads_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists leads_set_updated_at on public.leads;
create trigger leads_set_updated_at
before update on public.leads
for each row execute function public.set_leads_updated_at();

-- Durable scrape jobs are created by the hosted dashboard and claimed by the
-- GitHub Actions worker. The serverless function never owns a background job.
create table if not exists public.scrape_jobs (
    id uuid primary key default gen_random_uuid(),
    status text not null default 'queued'
        check (status in ('queued', 'running', 'completed', 'failed', 'cancelled')),
    requested_by text not null default '',
    options jsonb not null default '{}'::jsonb,
    log_tail jsonb not null default '[]'::jsonb,
    leads_saved integer not null default 0,
    error text,
    created_at timestamptz not null default now(),
    started_at timestamptz,
    finished_at timestamptz
);

create index if not exists scrape_jobs_status_created_idx
    on public.scrape_jobs (status, created_at);

alter table public.scrape_jobs enable row level security;
